<?php

namespace App\Mock\Shipment;

use App\Mock\AMockV2;

class DKPickupShipmentMockData extends AMockV2
{
    protected static function response1(): ?string
    {
        return '{
        "status": "ok",
        "data": {
          "id": "544916",
          "shipment_number": "1419067010824001",
          "created_at": "2024-08-01T07:47:45.000000+03:30",
          "pickup_warehouse_title": "پارتیان",
          "pickup_date": "2024-08-01T14:00:00.000000+03:30",
          "cost": 836771,
          "status": {
            "received": "دریافت شده"
          },
          "total_volume": null,
          "total_weight": null,
          "min_distance": null,
          "can_delete": false,
          "packages": {
            "22954251": {
              "id": 22954251,
              "package_number": "14190671010824001",
              "type": {
                "key": "order_fulfilment",
                "title": "سفارش"
              },
              "shipping_nature": {
                "1": "کوچک"
              },
              "show_print_label_package": false,
              "show_print_label_serials": false,
              "show_print_receive_receipt": false,
              "create_date": "2024-08-01T07:46:45.000000+03:30",
              "estimated_pickup_date": "2024-08-01T18:31:33.000000+03:30",
              "status": {
                "key": "received",
                "title": "دریافت شده"
              }
            }
          },
          "packages_count": 1,
          "time_scope": {
            "start": 14,
            "end": 16
          }
        }
      }';
    }

    protected static function response2(): ?string
    {
        return parent::response2(); // TODO: Change the autogenerated stub
    }

    protected static function response3(): ?string
    {
        return parent::response3(); // TODO: Change the autogenerated stub
    }
}